# Generated by Django 4.2.9 on 2026-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="auto_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidate",
            name="completeness_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="experience_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="optional_skills_matched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="optional_skills_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="candidate",
            name="required_skills_matched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="required_skills_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("fulltime", "Full Time"),
                    ("parttime", "Part Time"),
                    ("internship", "Internship"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="fulltime",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="min_cgpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="min_education",
            field=models.CharField(
                choices=[
                    ("any", "Any Degree"),
                    ("10th", "10th Pass"),
                    ("12th", "12th Pass"),
                    ("diploma", "Diploma"),
                    ("bca", "BCA / B.Sc"),
                    ("btech", "B.Tech / B.E."),
                    ("mca", "MCA / M.Sc"),
                    ("mtech", "M.Tech / M.E."),
                    ("mba", "MBA"),
                    ("phd", "PhD"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="min_experience",
            field=models.CharField(
                choices=[
                    ("any", "Any / Not Required"),
                    ("fresher", "Fresher Only"),
                    ("1", "1+ Year"),
                    ("2", "2+ Years"),
                    ("3", "3+ Years"),
                    ("5", "5+ Years"),
                    ("8", "8+ Years"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="optional_skills",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="required_skills",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Package (LPA)"),
                    ("monthly", "Monthly Salary"),
                    ("stipend", "Stipend (Internship)"),
                    ("undisclosed", "Not Disclosed"),
                ],
                default="undisclosed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("auto_rejected", "Auto Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="salary_range",
            field=models.CharField(default="not_disclosed", max_length=50),
        ),
    ]
